/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vissible;

/**
 *
 * @author sscerbatiuc
 */
public class CalculatorWithUserInput  extends javax.swing.JFrame  {

    /**
     * Creates new form MainWindow
     */
    public CalculatorWithUserInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        secondNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calculateSum = new javax.swing.JButton();
        allResult = new javax.swing.JLabel();
        openSubMenuBtn = new javax.swing.JButton();
        calculateDif = new javax.swing.JButton();
        calculateMultiple = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        calculateDiv = new javax.swing.JButton();
        calculateRem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNumberActionPerformed(evt);
            }
        });

        jLabel1.setText("Calculator");

        secondNumber.setName("secondNumber"); // NOI18N
        secondNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondNumberActionPerformed(evt);
            }
        });

        jLabel2.setText("First number");

        jLabel3.setText("Second number");

        calculateSum.setText("+");
        calculateSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateSumActionPerformed(evt);
            }
        });

        allResult.setText("Result");

        openSubMenuBtn.setText("Back to control pannel");
        openSubMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSubMenuBtnActionPerformed(evt);
            }
        });

        calculateDif.setText("-");
        calculateDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateDifActionPerformed(evt);
            }
        });

        calculateMultiple.setText("x");
        calculateMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMultipleActionPerformed(evt);
            }
        });

        jLabel4.setText("Operation:");

        calculateDiv.setText("/");
        calculateDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateDivActionPerformed(evt);
            }
        });

        calculateRem.setText("Rest");
        calculateRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateRemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(openSubMenuBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(secondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(allResult)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculateSum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculateDif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculateMultiple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculateDiv)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculateRem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(secondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateSum)
                    .addComponent(calculateDif)
                    .addComponent(jLabel4)
                    .addComponent(calculateMultiple)
                    .addComponent(calculateDiv)
                    .addComponent(calculateRem))
                .addGap(28, 28, 28)
                .addComponent(allResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(openSubMenuBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateSumActionPerformed
       try{if (this.firstNumber != null && this.secondNumber != null) {
            this.allResult.setText(String.valueOf(Integer.parseInt(this.firstNumber.getText()) + Integer.parseInt(this.secondNumber.getText())));
        }}catch(NumberFormatException e){
        this.allResult.setText("You must introduce only Numbers");
        } 

    }//GEN-LAST:event_calculateSumActionPerformed

    private void openSubMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSubMenuBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ControlPannel().setVisible(true);
    }//GEN-LAST:event_openSubMenuBtnActionPerformed

    private void calculateDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateDifActionPerformed
        try{if (this.firstNumber != null && this.secondNumber != null) {
            this.allResult.setText(String.valueOf(Integer.parseInt(this.firstNumber.getText()) - Integer.parseInt(this.secondNumber.getText())));
        }}catch(NumberFormatException e){
        this.allResult.setText("You must introduce only Numbers");
        }
    }//GEN-LAST:event_calculateDifActionPerformed

    private void calculateMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMultipleActionPerformed
       try{if (this.firstNumber != null && this.secondNumber != null ) {
            this.allResult.setText(String.valueOf(Integer.parseInt(this.firstNumber.getText()) * Integer.parseInt(this.secondNumber.getText())));
        }}catch(NumberFormatException e){
        this.allResult.setText("You must introduce only Numbers");
        }
//       try{ if(this.secondNumber != null)
//       }catch(Exception a ){
//           this.allResult.setText("can't divide by zero");
//       }
    }//GEN-LAST:event_calculateMultipleActionPerformed

    private void calculateDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateDivActionPerformed
                

        
        
        
        try{if (this.firstNumber != null && this.secondNumber != null  ) {
         try{   this.allResult.setText(String.valueOf(Integer.parseInt(this.firstNumber.getText()) /  Integer.parseInt(this.secondNumber.getText())));}
         catch(ArithmeticException p){
         this.allResult.setText("Cannot divide by zero");
         }
        }}catch(NumberFormatException e){
        this.allResult.setText("You must introduce only Numbers");
        }
    
    }//GEN-LAST:event_calculateDivActionPerformed

    private void calculateRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateRemActionPerformed
       try{if (this.firstNumber != null && this.secondNumber != null ) {
            this.allResult.setText(String.valueOf(Integer.parseInt(this.firstNumber.getText()) % Integer.parseInt(this.secondNumber.getText())));
        }}catch(NumberFormatException e){
        this.allResult.setText("You must introduce only Numbers");
        }
    }//GEN-LAST:event_calculateRemActionPerformed

    private void firstNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNumberActionPerformed
        
    }//GEN-LAST:event_firstNumberActionPerformed

    private void secondNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorWithUserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorWithUserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorWithUserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorWithUserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorWithUserInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allResult;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateDif;
    private javax.swing.JButton calculateDiv;
    private javax.swing.JButton calculateMultiple;
    private javax.swing.JButton calculateRem;
    private javax.swing.JButton calculateSum;
    private javax.swing.JTextField firstNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton openSubMenuBtn;
    private javax.swing.JTextField secondNumber;
    // End of variables declaration//GEN-END:variables
}
