/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vissible;

import javax.swing.table.DefaultTableModel;
import HumanResoursePart.Employee;
import java.util.ArrayList;
import Vissible.AddViewPannel;
import HumanResoursePart.HumanServicePart.EmployeeService;
import com.toedter.calendar.JDateChooser;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell
 */
public class MainViewPannel extends javax.swing.JFrame {

//    }
    public MainViewPannel() {
        initComponents();
        addRowToJTable();
        EmployeeService.Showlist();
        EmployeeService.NewLine();
    }

    EditViewPannel jtRowData = new EditViewPannel();
    
    
    
    public void addRowToJTable() {
        DefaultTableModel model = (DefaultTableModel) tabelVar.getModel();

        EmployeeService employee = new EmployeeService();

        ArrayList<Employee> list = employee.ShowList();
        Object rowData[] = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            
            
            rowData[0] = i+1;
            rowData[1] = list.get(i).getNume();
            rowData[2] = list.get(i).getPrenume();
            rowData[3] = list.get(i).getDataNasteri();
            rowData[4] = list.get(i).getSpecialitate();
               
            model.addRow(rowData);
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelVar = new javax.swing.JTable();
        addButton = new java.awt.Button();
        edit = new java.awt.Button();
        backToControlPannel = new java.awt.Button();
        deleteButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelVar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Nume", "Prenume", "Data nasteri", "Specialitate"
            }
        ));
        jScrollPane1.setViewportView(tabelVar);

        addButton.setLabel("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        edit.setActionCommand("edit&Delete");
        edit.setLabel("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        backToControlPannel.setLabel("Back to Control Pannel");
        backToControlPannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToControlPannelActionPerformed(evt);
            }
        });

        deleteButton.setActionCommand("Delete");
        deleteButton.setLabel("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("*For Edit/Delete, first select the Employee.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(backToControlPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToControlPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        this.dispose();
        new AddViewPannel().setVisible(true);

    }//GEN-LAST:event_addButtonActionPerformed

    private void backToControlPannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToControlPannelActionPerformed
        this.dispose();
        new ControlPannel().setVisible(true);
    }//GEN-LAST:event_backToControlPannelActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       try{ int index = tabelVar.getSelectedRow();
        
        DefaultTableModel modelForEdit = (DefaultTableModel) tabelVar.getModel();
        //TableModel modelForEdit = tabelVar.getModel();
        
        String eNume = modelForEdit.getValueAt(index, 1).toString();
        String ePrenume = modelForEdit.getValueAt(index, 2).toString();
        Date date = null;
        try {
             date = new SimpleDateFormat("dd/MM/yyyy").parse((String)modelForEdit.getValueAt(index, 3));
           // JDateChooser.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(MainViewPannel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        String eSpecialitate = modelForEdit.getValueAt(index, 4).toString();
        //  Object eSpecialitate = modelForEdit.getValueAt(index, 3);
          
          
        jtRowData.setVisible(true);
        jtRowData.pack();
        jtRowData.setLocationRelativeTo(null);
        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        jtRowData.numeEditVar.setText(eNume);
        jtRowData.prenumeEditVar.setText(ePrenume);
        jtRowData.dateBirthEditVar.setDate(date);
        jtRowData.functiaEditVar.setSelectedItem(eSpecialitate);
        jtRowData.indexEdit = index;
       
        
        this.dispose();
        
        }
       catch(Exception ex){
       JOptionPane.showMessageDialog(rootPane, "Select first the employee which you want to edit");
       
       }
        
        
        
//        new EditViewPannel().setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        DefaultTableModel modelForDelete = (DefaultTableModel) tabelVar.getModel();
        try {
            int SelectedRowIndex = tabelVar.getSelectedRow();
            modelForDelete.removeRow(SelectedRowIndex);
            EmployeeService.RemoveFromList(SelectedRowIndex);
            this.dispose();
            new MainViewPannel().setVisible(true);
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(rootPane, "Select first the employee which you want to delete");
        }


    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainViewPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainViewPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainViewPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainViewPannel().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addButton;
    private java.awt.Button backToControlPannel;
    private java.awt.Button deleteButton;
    private java.awt.Button edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelVar;
    // End of variables declaration//GEN-END:variables

}
